-- schema.sql

-- Client Table
CREATE TABLE Client (
	ClientID SERIAL PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Email VARCHAR(100) UNIQUE NOT NULL,
	PhoneNumber VARCHAR(20),
	PasswordHash VARCHAR(255) NOT NULL,
	CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	Role VARCHAR(20) DEFAULT 'Client' NOT NULL
);

-- Pet Table
CREATE TABLE Pet (
	PetID SERIAL PRIMARY KEY,
	ClientID INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Breed VARCHAR(50),
	Age INT,
	Notes TEXT,
	CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ClientID) REFERENCES Client(ClientID) ON DELETE CASCADE
);

-- Service Table
CREATE TABLE Service (
	ServiceID SERIAL PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Description TEXT,
	Price DECIMAL(10, 2) NOT NULL,
	DurationMinutes INT
);

-- Appointment Table
CREATE TABLE Appointment (
	AppointmentID SERIAL PRIMARY KEY,
	ClientID INT NOT NULL,
	PetID INT NOT NULL,
	ServiceID INT NOT NULL,
	AppointmentTime TIMESTAMP WITH TIME ZONE NOT NULL,
	Status VARCHAR(20) DEFAULT 'Scheduled', -- e.g., Scheduled, Completed, Canceled
	Notes TEXT,
	ReminderSent BOOLEAN DEFAULT FALSE,
	CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ClientID) REFERENCES Client(ClientID) ON DELETE CASCADE,
	FOREIGN KEY (PetID) REFERENCES Pet(PetID) ON DELETE CASCADE,
	FOREIGN KEY (ServiceID) REFERENCES Service(ServiceID)
);

-- Invoice Table
CREATE TABLE Invoice (
	InvoiceID SERIAL PRIMARY KEY,
	AppointmentID INT NOT NULL,
	Amount DECIMAL(10, 2) NOT NULL,
	Status VARCHAR(20) DEFAULT 'Unpaid', -- e.g. Unpaid, paid
	DueDate DATE,
	CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (AppointmentID) REFERENCES Appointment(AppointmentID) ON DELETE CASCADE
);

-- Notification Table
CREATE TABLE Notification (
    NotificationID SERIAL PRIMARY KEY,
    ClientID INT NOT NULL,
    Message TEXT NOT NULL,
    IsRead BOOLEAN DEFAULT FALSE,
    Link VARCHAR(255), -- Optional link for navigation
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ClientID) REFERENCES Client(ClientID) ON DELETE CASCADE
);
